var photoText=[
				//first part
			  	[
			  		"This is the First Part of the Story </br></br> The Bigning...",
			  		"so on 13/07/20111 , You praposes Me",
			  		"You always dreamed of flying with me",
			  		"but our journey not begins here,it is start from Navodaya",
			  		"I came Your home on 22/06/2011",
			  		"after that I met with your family",
			  		"and your friends",
			  		"Yes, i made you sad many times",
			  		"But I wanted that you become mother of my baby.",
			  		"Thank You for Watching This</br></br> visit tomorrow for Next Part",
			  	],
			  	[
			  		"Previously You had seen ",
			  		"PART II</br></br>First Meeting",
			  		"You came to Kota when I left it",
			  		"Then you started to be beautiful for me",
			  		"you had tried new outfits",
			  		"new hair styles",
			  		"whenever you had felt loneliness",
			  		"you had liked to visit mall",
			  		"developed your love for teddy",
			  		"and you hugged it by assuming it as me.",
			  		"After leaving home you had made new friends",
			  		"visited new places",
			  		"enjoy every festival",
			  		"On 26/12/2012 I and our friend",
			  		"had come to meet my innocent",
			  		"and cute girlfriend",
			  		"and also to meet with your di",
			  		"and your jeeju",
			  		"That time I spent some lovely",
			  		"and unforgetable moment with you",
			  		"Thank You for Watching This</br></br> visit tomorrow for Next Part",
			  	],
			  	[
			  		"Priviously You had seen",
			  		"PART III</br></br>Garba Nights",
			  		"Your destiny took you",
			  		"from Kota",
			  		"to Vadodra",
			  		"in my view",
			  		"in the time you spent in vododra",
			  		"you had changed alot",
			  		"from a simple looking girl",
			  		"to a beautiful girl",
			  		"from a संस्कारी girl",
			  		"to moder sexy girl",
			  		"you had got the title of Miss fresher",
			  		"did you know baby",
			  		"this is the pic which my mom saw in my phone",
			  		"This shopping loving girl",
			  		"also participates in running",
			  		"and in garba and in others events",
			  		"You were looking so cute",
			  		"and slim that",
			  		"I couldn't wait to meet my sweatheart",
			  		"to enjoy some moments with you",
			  		"although i looks very bad",
			  		"but this beautiful",
			  		"and amazing girl",
			  		"danceed with me in garba.",
			  		"In this outfit",
			  		"you were looking so beautiful",
			  		"sooo sexy ",
			  		"soo innocent and cute altogether that",
			  		"this pic of yours became my favourite.",
			  		"Here we kissed first time",
			  		"After this we meet",
			  		"again in kota",
			  		"and in surat also",
			  		"Thank You for Watching This</br></br> visit tomorrow for Next Part",
			  	],
			  	[
			  		"Priviously You had seen",
			  		"PART IV</br></br>Birth Day",
			  		"Although you are not too healthy",
			  		"but you know how to look beautiful",
			  		"Your every pic is attractive",
			  		"no matter you are ready for pic",
			  		"or not.",
			  		"You and your family",
			  		"frequently plans for a trip",
			  		"like this naturally beautiful",
			  		"religious imortant place Keadarnath.",
			  		"Where you clicked some awesome pics",
			  		"like playing with ice",
			  		"enjoying the water etc.",
			  		"actully this pic is looked like a perfect wallpaper.",
			  		"We again met in Indore",
			  		"where you take your best hair cut",
			  		"we had visited malls",
			  		"and parks of Indore",
			  		"and Most Importantly",
			  		"first time we celebrated your bdy together.",
			  		"We also visited Khajuraho",
			  		"and had taken lunch and some rest",
			  		"where I had eaten most costly food of my life",
			  		"and we had clicked beautiful pictures of ourself.",
			  		"Thank You for Watching This</br></br> visit tomorrow for Next Part",
			  	],
			  	[
			  		"Priviously You had seen",
			  		"PART V</br></br>Di Annivarsary",
			  		"There is two hobbies of my beautiful girlfriend",
			  		"first is shopping",
			  		"and second is hangout with friends",
			  		"wherever you  go",
			  		"you clicks many pictures",
			  		"whether it is shopping mall.",
			  		"or a historical place like Dhubela",
			  		"and whether you are wearing a traditional salwar suit",
			  		"or some modern fashioned outfits like shorts.",
			  		"Nither I spent much time with",
			  		"my always frustated girlfriend",
			  		"nor I celebrated festival",
			  		"like diwali with you.",
			  		"But every moment which I",
			  		"spent with you is",
			  		"memorable for my life.",
			  		"No matter where we are",
			  		"whether we are in your home",
			  		"or whether we are in our friends home",
			  		"and whether we are far away from each other",
			  		"or too close",
			  		"whether it is morning",
			  		"or noon",
			  		"or evening",
			  		"we,both of us",
			  		"love each other.",
			  		"Every time whwn i see this environmentalist",
			  		"wearing a sari like a",
			  		"young and mature lady",
			  		"I fantasize you",
			  		"as my future wife",
			  		"Thank You for Watching This</br></br> visit tomorrow for Next Part",
			  	],
			  	[
			  		"Priviously You had seen",
			  		"PART VI</br></br>Hotal",
			  		"As time passes",
			  		"Your image of cute and innocent girl",
			  		"is changed into sexy and",
			  		"young lady in my mind.",
			  		"when you reached Amarkantak",
			  		"you became more stylish",
			  		"and more cooperative.",
			  		"Even the communication between us decreases",
			  		"Our relation continues",
			  		"even our relation become more strong than before",
			  		"I become sleeping pill of this girl",
			  		"and she takes away my sleep.",
			  		"Now as you have your own car",
			  		"your trips with friends",
			  		"increasing day by day.",
			  		"Your fashion sense",
			  		"and your beautiful face",
			  		"make me crazy for you.",
			  		"Room No.-127, Hotal Hari Piorke",
			  		"Our first stay in hotal.",
			  		"you are too happy those days",
			  		"I enjoyed every moment of those days with you",
			  		"whether it is day or night.",
			  		"I take my best sleep ever",
			  		"and also ready for many night without sleep",
			  		"for such a moment</br>(My loving baby in my arms).",
			  		"You looks very sexy in my Shirt",
			  		"You eat my brain more than the food.",
			  		"You always want to try somthing new with your look",
			  		"aren't you..?",
			  		"Thank You for Watching This</br></br> visit tomorrow for Next Part",
			  	],
			  	[
			  		"Priviously You had seen",
			  		"PART VII</br></br>Live In",
			  		"First of all happy bdy my love",
			  		"As you already know that",
			  		"i like two things in body the most",
			  		"first is your beautiful face",
			  		"and other is your long silky hairs",
			  		"You looks beautiful",
			  		"but together be are awesome",
			  		"No matter how thin or fat you are",
			  		"no matter you shorter or taller than me",
			  		"I am alwys able to lift you up in my arms",
			  		"As today you are with me",
			  		"I promise you that",
			  		"no matter how you looks",
			  		"no matter what you become in future",
			  		"I always try to keep you happy",
			  		"and love you from the bottom of my heart",
			  		"and in my all life I am with you",
			  	]
			  ]
